---
{{- if and .Values.homebridge.credentials.username .Values.homebridge.credentials.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "homebridge-prometheus-exporter.fullname" . }}
  labels:
    app: {{ template "homebridge-prometheus-exporter.name" . }}
    chart: {{ template "homebridge-prometheus-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  HOMEBRIDGE_USERNAME: {{ .Values.homebridge.credentials.username | b64enc | quote }}
  HOMEBRIDGE_PASSWORD: {{ .Values.homebridge.credentials.password | b64enc | quote }}
{{- end }}
{{- if and .Values.homebridge.sealedCredentials.username .Values.homebridge.sealedCredentials.password -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "homebridge-prometheus-exporter.fullname" . }}
  labels:
    app: {{ template "homebridge-prometheus-exporter.name" . }}
    chart: {{ template "homebridge-prometheus-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  encryptedData:
    HOMEBRIDGE_USERNAME: {{ .Values.homebridge.sealedCredentials.username | quote }}
    HOMEBRIDGE_PASSWORD: {{ .Values.homebridge.sealedCredentials.password | quote }}
  template:
    metadata:
      name: {{ template "homebridge-prometheus-exporter.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ template "homebridge-prometheus-exporter.name" . }}
        chart: {{ template "homebridge-prometheus-exporter.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
{{- end }}
