{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "homebridge-prometheus-exporter.serviceAccountName" . }}
  labels:
      app: {{ template "homebridge-prometheus-exporter.name" . }}
      chart: {{ template "homebridge-prometheus-exporter.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end -}}
